services:
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: ./packages/Perplexica
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: ./packages/Perplexica
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

  aider:
    build:
      context: ./packages/aider
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.12
    depends_on:
      - ollama
    ports:
      - 5000:5000
    networks:
      - perplexica-network
    restart: unless-stopped

  agent-zero:
    build:
      context: ./packages/agent-zero
      dockerfile: ./docker/Dockerfile
      args:
        - PYTHON_VERSION=3.12
    depends_on:
      - ollama
    ports:
      - 5001:5001
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore: